import type { Metadata } from "next";
import { Inter } from "next/font/google";
import  "bootstrap/dist/css/bootstrap.min.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "./globals.css";
import Topbar from "@/components/topbar/Topbar"
import Headers from "@/components/header/Header"
import Footer from "@/components/footer/Footer"
import { SpeedInsights } from "@vercel/speed-insights/next"


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Moga Medicity",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <Topbar />
        <Headers />
        {children}
        <SpeedInsights />
        <Footer />
        </body>
    </html>
  );
}
